

CREATE TABLE Poststed (
	Postnr VARCHAR(4) NOT NULL,
	Poststed VARCHAR(50) NOT NULL,
	PRIMARY KEY (Postnr)
);

CREATE TABLE Kunde (
	Kid INT(11) NOT NULL AUTO_INCREMENT,
	Fornavn VARCHAR(50) NOT NULL,
	Etternavn VARCHAR(50) NOT NULL,
	Adresse VARCHAR(50) NOT NULL,
	Postnr VARCHAR(4) NOT NULL,
	Telefonnr VARCHAR(8) NOT NULL,
	Epost VARCHAR(50) NOT NULL,
	PRIMARY KEY (Kid),
	FOREIGN KEY (Postnr) REFERENCES Poststed(Postnr)
);

CREATE TABLE Pakke (
	Pid INT(11) NOT NULL AUTO_INCREMENT,
	Kid INT(11) NOT NULL,
	Volum DECIMAL(10, 0) NOT NULL,
	Vekt  DECIMAL(10, 0) NOT NULL,
	PRIMARY KEY (Pid),
	FOREIGN KEY (Kid) REFERENCES Kunde(Kid)
);

INSERT INTO Poststed VALUES ('5225', 'Nesttun');